config:
  {{PROJECT}}-infrastructure:project: {{PROJECT}}-prod
  {{PROJECT}}-infrastructure:environment: prod
  {{PROJECT}}-infrastructure:domain: {{DOMAIN}}
  digitalocean:token:
    secure: REPLACE_WITH_ENCRYPTED_TOKEN
